name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y graphviz graphviz-dev
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: python ./scripts/run_tests.py
