name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies and run tests
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y graphviz graphviz-dev
        pip install pygraphviz
        antlr4 -Dlanguage=Python3 project/language.g4 -visitor
        python ./scripts/run_tests.py
